server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/whiteboard?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Senthil2004$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.websocket.path=/ws

jwt.secret=TbqfLse6uJIbJ3iXiBQarq3zMglg8E/PTyoO35YOwbntcOiygKD4FTBIjwAaYBM0
jwt.expiration-ms=86400000

